title: Blog Bibliotheks- und Archivinformatik
author: Selina
email: selina.lanz@fhgr.ch
description: > # this means to ignore newlines

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
